apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy                #echo -n mongouser | base64   -< muss so verschluesselt sein
  mongo-password: bW9uZ29wYXNzd29yZA==    #verschluesselung dient nicht der geheimhaltung, sondern damit man alle datentypen inkl files als zeichenkette interpretieren kann